FlowingCode/CommonsDemo

src/main/java/com/flowingcode/vaadin/addons/demo/impl/TabbedDemoImpl.java
When changing between tabs after switching any of the layout checkboxes, the layout did not updated accordingly.
Fix: layout works well while switching rapidly between tabs and orientation/show code checkboxes.
=> Fix splitLayout not updating its layout config

src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeView.java, src/main/resources/META-INF/resources/frontend/styles/commons-demo/shared-styles.css, src/test/java/com/flowingcode/vaadin/addons/demo/Demo.java, src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemo.java
This change is Backwards Compatible™ (the change in Demo.java and DemoSource.java is unrelated to the replacement of gist-it, those URL were wrong already). The chosen parser is not perfect, but it fits the bill.
=> Replace Gist-it with polymer-code-highlighter

pom.xml, src/main/java/com/flowingcode/vaadin/addons/GithubLink.java, src/main/java/com/flowingcode/vaadin/addons/demo/DemoSource.java, src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java, src/test/java/com/flowingcode/vaadin/addons/demo/Demo.java, src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemoDefault.java
If no `value` is specified, and the demo view is annotated with `@GithubLink`, the source URL defaults to the location of the annotated class under `src/java/test` in the master branch of the repository.
=> feat: allow `@DemoSource` URL to default to the location of the class.

src/main/resources/META-INF/resources/frontend/code-viewer.ts
Remove unused import of `@vaadin/vaadin-tabs` which causes issues when compiling with Vaadin 24
=> fix: remove unused import of @vaadin/vaadin-tabs

pom.xml, src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeView.java
Add `@NpmPackage` for `lit`, which seems to be necessary in Vaadin 14 after 1febde79
Also, add profiles for V23 and V24
=> Vaadin profiles

src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
If `codeCB` is unchecked, and the screen resolution is not mobile, it should remain unchecked
=> fix: preserve source visibility if not mobile

src/main/resources/META-INF/resources/frontend/code-viewer.ts, src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemoDefault.java
Remove the following boilerplate code from source snippets:
- The package declaration
- All lines with a `// hide-source` comment.
- The `@Route` annotation and its import.
- The `@PageTitle` annotation and its import.
- The `@DemoSource` annotation and its import.
=> feat: cleanup source snippets

src/main/java/com/flowingcode/vaadin/addons/DevSourceRequestHandler.java, src/main/java/com/flowingcode/vaadin/addons/DevSourceRequestHandlerInitializer.java, src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeView.java, src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
=> feat: use local demo sources in development mode

pom.xml, src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeView.java, src/main/java/com/flowingcode/vaadin/addons/demo/SplitLayoutDemo.java, src/main/java/com/flowingcode/vaadin/addons/demo/VaadinVersion.java, src/main/resources/META-INF/resources/frontend/code-viewer.ts, src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemoDefault.java
show-source is implemented as described in #42 
Support for conditional code (#43) uses C-inspired directives `#if`, `#elif` (else-if), `#else` and `#endif`
Syntax: `#if variable operator value` 
- Supported variables are "vaadin" and "flow". (Note that Vaadin 14 uses Flox 1.x.x)
- Supported operators are `lt`, `le`, `ne`, `eq`, `gt`, `ge` (Operator names borrowed from Fortran)
- Value is a one-digit (`x`), two-digit (`x.y`) or three-digit (`x.y.z`) version number 
Implementation: The `cleanupCode` algorithm was improved in order to preprocess the sources before feeding them to prism.js. The implementation uses two stacks: a stack of guards (`guards`) and a stack of directives (the `stack`). Guards are three-valued: `istrue`, `isfalse` or `wastrue`. 
When an `#if` directive is found, it's …
=> feat: add support for show-code and conditional code 

src/main/resources/META-INF/resources/frontend/code-viewer.ts, src/test/java/com/flowingcode/vaadin/addons/demo/it/AbstractSourceCodeViewerIT.java, src/test/java/com/flowingcode/vaadin/addons/demo/it/ConditionalSourceCodeViewerIT.java, src/test/java/com/flowingcode/vaadin/addons/demo/it/SourceCodeViewerIT.java, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionEq.java, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionEq.txt, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionGe.java, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionGe.txt, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionGt.java, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionGt.txt, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionLe.java, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionLe.txt, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionLt.java, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionLt.txt, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionNe.java, src/test/resources/com/flowingcode/vaadin/addons/demo/it/ConditionNe.txt
The current implementation of version comparison in #44 follows a lexicographic order, yielding consistent yet non-intuitive outcomes (`23.0.0` is greater than `23` and `23.0.0` is not equal to `23`)
https://github.com/FlowingCode/CommonsDemo/blob/ef035156d29c5a63227d8bb472717f510afbf711/src/main/resources/META-INF/resources/frontend/code-viewer.ts#L348-L359
Instead, we should only compare the provided digits, so that `23.0.0` is _not_ greater than `23`, and `23.1.0` is _equals_ to 23.
```diff
-    if (aa.length<bb.length) return -1; 
-    if (aa.length>bb.length) return +1; 
return 0; 
```
Strictly, "equals" will be implemented as "is contained in" (23.0.0 is-contained-in 23) and "greater-or-equal" will be implemented as "precedes or is contained in" ("23.4.5 precedes 24", 23.4.5 …
=> Fix code-viewer __compare

pom.xml
I changed CI in order to use amazon-corretto and it seems that now it flags several javadoc errors, thus I think it's better to explicitly configure this plugins in pom, instead of relying on command line.
=> build: attach sources and javadoc

pom.xml, src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeViewer.java, src/main/resources/META-INF/resources/frontend/code-viewer.ts, src/test/java/com/flowingcode/vaadin/addons/demo/Demo.java, src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemoHighlight.java, src/test/resources/META-INF/resources/frontend/highlight-demo.css
Add support for highlighting source code fragments in order to emphasize a section of the code snippet. A block is delimited by `// begin-block name` and `// end-block` comments. Nested blocks are not supported.
```
// begin-block first
Div first = new Div(new Text("First"));
SourceCodeViewer.highlightOnHover(first, "first");
first.addClassName("dashed"); // hide-source
add(first);
// end-block
```
=> Add support for highlighting source code fragments

pom.xml, src/main/java/com/flowingcode/vaadin/addons/demo/DemoSource.java, src/main/java/com/flowingcode/vaadin/addons/demo/MultiSourceCodeViewer.java, src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeTab.java, src/main/java/com/flowingcode/vaadin/addons/demo/SourcePosition.java, src/main/java/com/flowingcode/vaadin/addons/demo/SplitLayoutDemo.java, src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
=> feat: add support to change source code position

src/main/resources/META-INF/resources/frontend/code-viewer.ts
Scroll to the last line before scrolling to the first line, so that the whole block is moved into view (which improves the behavior when the first line was already visible while the last lines aren't)
=> fix: improve autoscroll to highlighted block

pom.xml, src/main/java/com/flowingcode/vaadin/addons/demo/EnhancedRouteTabs.java, src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
Requires https://github.com/FlowingCode/EnhancedTabs/pull/8
=> fix: add workaround for RouterLinks

src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeViewer.java
=> fix: keep sources tab visible when scrolling

README.md, src/main/java/com/flowingcode/vaadin/addons/demo/MultiSourceCodeViewer.java, src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeViewer.java, src/main/resources/META-INF/resources/frontend/code-viewer.ts, src/test/java/com/flowingcode/vaadin/addons/demo/AdditionalSources.java, src/test/java/com/flowingcode/vaadin/addons/demo/MultiSourceDemo.java
Close #96
A fragment is highlighted either by calling `SourceCodeViewer.highlight(filenameAndId)` or when clicking/hovering a component that has been configured with `SourceCodeViewer.highlightOnClick` or `SourceCodeViewer.highlightOnHover`, where `filenameAndId` is the name of the fragment. If the component is in an additional source file, `filenameAndId` can be given as a string in the format `filename#id`. If no `'#'` is present, it is assumed that the identifier corresponds to a block in the first source panel.
=> feat: add support for multiple source highlighting

src/main/java/com/flowingcode/vaadin/addons/demo/EnhancedRouteTabs.java
Also, require a space before "Demo", so that other forms such as "Videodemo" would not be matched.
=> Do not remove suffix from "Basic Demo" or "Demo"

pom.xml, src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java, src/main/java/com/flowingcode/vaadin/addons/demo/ThemeChangeObserver.java
=> feat: add ThemeChangeObserver

pom.xml, src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
Store the selected theme in session, so that it's persisted when the user switches tabs.
=> feat: store theme in session
