pom.xml
src/main/java/com/flowingcode/vaadin/addons/GithubLink.java
src/main/java/com/flowingcode/vaadin/addons/demo/DemoSource.java
src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeView.java
src/main/java/com/flowingcode/vaadin/addons/demo/SplitLayoutDemo.java
src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
src/main/resources/META-INF/resources/frontend/styles/commons-demo/shared-styles.css
src/test/java/com/flowingcode/vaadin/addons/demo/Demo.java
src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemo.java

The tab label and source code URL are retrieved from the `PageTitle` and `DemoSource` annotations in the demo class.

Add annotation based configuration

---

pom.xml
src/main/java/com/flowingcode/vaadin/addons/demo/RouteTabs.java
src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
src/test/java/com/flowingcode/vaadin/addons/demo/Demo.java
src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemo.java
src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemoDefault.java

Boolmarkable tabs

---

src/main/java/com/flowingcode/vaadin/addons/demo/RouteTabs.java
src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java

Fallback to legacy demo if there is no "first route"

Fallback to legacy demo

---

pom.xml

No breaking change remains after the last changes.

build: set version to 3.4.0-SNAPSHOT

---

src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
src/main/resources/META-INF/resources/frontend/toggle-theme.js

feat: add feature to toggle between light & dark theme

---

src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
src/main/resources/META-INF/resources/frontend/styles/commons-demo/shared-styles.css

fix: position footer at bottom

---

src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java

Display source code divider horizontally in portrait mode and hide source code on mobile devices
Close #8

feat: change default source code visibility and divider behaviour

---

pom.xml
src/main/java/com/flowingcode/vaadin/addons/demo/DemoHelper.java
src/main/java/com/flowingcode/vaadin/addons/demo/DemoHelperRenderer.java
src/main/java/com/flowingcode/vaadin/addons/demo/DemoHelperViewer.java
src/main/java/com/flowingcode/vaadin/addons/demo/DialogDemoHelperViewer.java
src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
src/test/java/com/flowingcode/vaadin/addons/demo/LegacyDemo.java
src/test/java/com/flowingcode/vaadin/addons/demo/LegacyDemoHelperRenderer.java
src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemo.java
src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemoHelperRenderer.java

feature: add help icon to tabs

---

src/main/resources/META-INF/resources/frontend/code-viewer.ts

Use a short version of the license header in code snippets, so that the license doesn't take most of available space.
This feature replaces the long header with a short copyright statement and link to the license, provided that all of the following conditions are met:
- That the license header is formatted with maven license plugin (using default delimiters).
- That the license header is added before the `package` declaration.
- That the choosen license is Apache v2.0

feat: use short license header

---

src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
src/test/java/com/flowingcode/vaadin/addons/demo/AdHocDemo.java
src/test/java/com/flowingcode/vaadin/addons/demo/AdHocSource.java

fix: default to GithubLink when DemoSource is set to /src/test

---

src/main/resources/META-INF/resources/frontend/code-viewer.ts
src/test/java/com/flowingcode/vaadin/addons/demo/it/SourceCodeViewerIT.java
src/test/resources/com/flowingcode/vaadin/addons/demo/it/CleanupOverride.java
src/test/resources/com/flowingcode/vaadin/addons/demo/it/CleanupOverride.txt

fix: preserve lines commented with show-source

---

src/main/resources/META-INF/resources/frontend/code-viewer.ts

fix: cleanup @Ignore annotation

---

README.md
src/main/java/com/flowingcode/vaadin/addons/GithubBranch.java
src/main/java/com/flowingcode/vaadin/addons/demo/DemoSource.java

docs: document TabbedDemo and SourceCodeViewer features

---

README.md
src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeViewer.java
src/main/resources/META-INF/resources/frontend/code-viewer.ts
src/test/java/com/flowingcode/vaadin/addons/demo/SampleDemoHighlight.java

Add a shorthand for configuring a click listener that turns on highlighting.

feat: add highlightOnClick method

---

README.md
pom.xml
src/main/java/com/flowingcode/vaadin/addons/demo/DemoSource.java
src/main/java/com/flowingcode/vaadin/addons/demo/DemoSources.java
src/main/java/com/flowingcode/vaadin/addons/demo/MultiSourceCodeViewer.java
src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeTab.java
src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeViewer.java
src/main/java/com/flowingcode/vaadin/addons/demo/SplitLayoutDemo.java
src/main/java/com/flowingcode/vaadin/addons/demo/TabbedDemo.java
src/test/java/com/flowingcode/vaadin/addons/demo/MultiSourceDemo.java
src/test/resources/META-INF/resources/frontend/multi-source-demo.css

feat: allow multiple source code tabs

---

pom.xml

https://github.com/FlowingCode/AddonsDemo/issues/222
https://github.com/FlowingCode/AddonsDemo/issues/223

Make vaadin dependency optional and add profiles for snapshot versions

---

.gitignore
pom.xml
src/main/java/com/flowingcode/vaadin/addons/demo/SourceCodeViewer.java
src/main/resources/META-INF/resources/frontend/code-viewer.ts

build!: remove hardcoded lit dependency

---

src/main/resources/META-INF/resources/frontend/code-viewer.ts

fix: specify type of elem parameter

---

src/main/java/com/flowingcode/vaadin/addons/demo/DemoHelperViewer.java
src/main/java/com/flowingcode/vaadin/addons/demo/DialogDemoHelperViewer.java

fix: make DemoHelperViewer serializable

---

src/main/java/com/flowingcode/vaadin/addons/demo/MultiSourceCodeViewer.java

Requires https://github.com/FlowingCode/EnhancedTabs/pull/21
This PR updates the logic for tab retrieval since the current code does not work `EnhancedTabs`

fix: use EnhancedTabs::getTabs
